# Generated by Django 2.1.2 on 2018-10-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
