# Generated by Django 2.1.2 on 2018-10-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market_core', '0002_auto_20181029_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_transactions', to='mega_market_core.Geo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_transactions', to='mega_market_core.Item')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_transactions', to='mega_market_core.TargetUser')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_transactions', to='mega_market_core.Geo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_transactions', to='mega_market_core.Item')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_transactions', to='mega_market_core.TargetUser')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BUY', -1), ('SELL', 1)], max_length=5),
        ),
    ]
