# Generated by Django 2.1.2 on 2018-11-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market_core', '0003_auto_20181029_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='target_user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
